# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4561b9642316bee906c5c9f166a0e5f79a45795c002414220365da83474bbe25402473e653a3d4e0f336fb83e3323b89076e0f4b2a9e9b6d01be749cfaff1ac5

test:
  secret_key_base: 8ffea21ac5c3fe19c3fb92714363aa7dbfea721b5a6413e42a04195336ff71d8d44beef7477236754351569883eb5758d4f7ce7917dbad598526080b0906d1c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
